package:
  name: pathways
  version: {{ environ['VERSION'] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  script_env:
    - VERSION
    - CONDA_BLD_PATH

requirements:
  host:
    - python  >=3.10,<3.13
    - setuptools
  run:
    - python  >=3.10,<3.13
    - numpy <2.0.0
    - pathlib
    - pandas
    - scipy
    - xarray<=2024.2.0
    - premise
    - pyyaml
    - bw_processing
    - bw2calc==2.0.dev23
    - bw2data==4.0.dev59
    - datapackage
    - pyprind
    - platformdirs
    - fs
    - SALib
    - pydantic>=2.8.2
    - pyarrow
    - fastparquet
    - edges
test:
  imports:
    - pathways

about:
  home: https://github.com/polca/pathways
  license: BSD License
  summary: 'Scenario-level environmental impact assessment of energy systems and transition pathways.'
license_family: BSD
